### ISSUE TITLE
[SUGGEST] Direct message instead of replying in channel

### ISSUE THREAD

**Issue by lewtds** [tvtri96/HenryBot#9]
More discrete and personal, less spamming. But if we go with this approach then doing translation would not make much sense.

**Comment by MiikaSav** [comment]
I'd vote for replying in the same channel but in a thread instead of a new message. Less spam, the writer is still notified and others can still see if there's a need for a translation.

**Comment by tvtri96** [comment]
Will close this one as #10 is a better solution.
